name: Pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start timer
        id: start_timer
        run: |
         echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd angular/ && npm install
      - name: Run tests
        run: cd angular/ && npm run coverage

      - name: Stop timer
        if: failure()
        id: stop_timer
        run: |
          echo "STOP_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Check environment variables
        if: failure()
        run: |
          START_TIME=$(echo ${{ env.START_TIME }})
          STOP_TIME=$(echo ${{ env.STOP_TIME }})
          EXECUTION_TIME=$((STOP_TIME - START_TIME))
          HOURS=$((EXECUTION_TIME / 3600))
          MINUTES=$((EXECUTION_TIME % 3600 / 60))
          SECONDS=$((EXECUTION_TIME % 60))
          echo "EXECUTION_TIME_HOURS=$HOURS" >> $GITHUB_ENV
          echo "EXECUTION_TIME_MINUTES=$MINUTES" >> $GITHUB_ENV
          echo "EXECUTION_TIME_SECONDS=$SECONDS" >> $GITHUB_ENV
          echo "Execution time: $HOURS hours $MINUTES minutes $SECONDS seconds"

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI Pipeline Failure"
          body: |
            Pipeline failed
            Final execution time: ${{ env.EXECUTION_TIME_HOURS }} hours ${{ env.EXECUTION_TIME_MINUTES }} minutes ${{ env.EXECUTION_TIME_SECONDS }} seconds
          to: clutcherdenis@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}