name: Pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: PWD
        run: pwd
      - name: Change directory
        run: cd angular/ && pwd
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test